version: '3.5'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=python_coursework
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - TZ=Europe/Moscow
    volumes:
      - './db_init:/docker-entrypoint-initdb.d/'

  flask:
    #restart: always
    build: ./flask_server/
    ports:
      - "5000:80"
    volumes:
      - ./flask_server:/usr/src/app
    depends_on:
      - "postgres"
